name: nadavspi-ublue
description: my ublue image

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    install: 
      - awesome
      - kitty
      - volumeicon
      - gnome-keyring
      - Thunar
    remove:
      - firefox 
      - firefox-langpacks 

  - type: bling 
    install:
      - justfiles 
      - nix-installer 
      - 1password 

  - type: default-flatpaks
    system:
      install:
        - com.discordapp.Discord
        - com.github.Eloston.UngoogledChromium
        - com.github.tchx84.Flatseal
        - com.slack.Slack
        - io.mpv.Mpv
        - md.obsidian.Obsidian
        - net.codeindustry.MasterPDFEditor
        - org.fcitx.Fcitx5
        - org.flameshot.Flameshot
        - org.mozilla.firefox
        - org.pulseaudio.pavucontrol
        - us.zoom.Zoom

  - type: script
    scripts:
      - signing.sh
