name: nadavspi-ublue
description: my ublue image

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/coolj/awesome-luajit-nightly/repo/fedora-%OS_VERSION%/coolj-awesome-luajit-nightly-fedora-%OS_VERSION%.repo
    install: 
      - awesome
      - blueman
      - feh
      - flameshot
      - input-remapper
      - kitty
      - mpv
      - network-manager-applet
      - redshift
      - rofi
      - volumeicon
      - zsh
    remove:
      - firefox 
      - firefox-langpacks 

  - type: bling 
    install:
      - nix-installer 
      - 1password 

  - type: default-flatpaks
    system:
      install:
        - com.discordapp.Discord
        - com.github.Eloston.UngoogledChromium
        - com.github.tchx84.Flatseal
        - com.slack.Slack
        - md.obsidian.Obsidian
        - net.ankiweb.Anki
        - net.codeindustry.MasterPDFEditor
        - org.fcitx.Fcitx5
        - org.mozilla.firefox
        - org.pulseaudio.pavucontrol
        - us.zoom.Zoom

  - type: script
    scripts:
      - signing.sh

  - type: systemd
    system:
      enabled:
        - sshd.service
        - var-mnt-appdata.automount
        - var-mnt-backups.automount
        - var-mnt-data.automount
        - var-mnt-docker.automount
        - var-mnt-docs.automount
        - var-mnt-isos.automount
        - var-mnt-photos.automount
